events/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "events"
urlpatterns = [
    path('', views.events_page, name="index"),
    path('criar-evento/', views.create_event, name="create_event"),
    path('<int:event_id>/', views.event_detail, name="event_details"),
    path('<int:event_id>/buy', views.buy_ticket, name="buy_ticket"),
    path('login/', views.login_page, name="login"),
    path('signup/', views.signup_view, name="signup"),
    path('logout/', views.logout_view, name="logout")
]

eventsystem/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls'))
]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Category(models.Model):

    class Meta:
        db_table = "categories"

    name = models.CharField(200)

    def __str__(self):
        return self.name;

class Event(models.Model):

    class Meta:
        db_table = 'events'

    title = models.CharField(max_length=200)
    description = models.CharField(max_length=400)
    address = models.CharField(max_length=200)
    date = models.DateTimeField()
    date_release_tickets = models.DateField()
    number_ticket = models.IntegerField(default=10)
    categories = models.ManyToManyField(Category, related_name="events")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="events")

    def __str__(self):
        return self.title


class Registration(models.Model):

    class Meta:
        db_table = 'registrations'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="registrations")
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

class Ticket(models.Model):

    class Meta:
        db_table = 'tickets'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tickets")
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="tickets")
    code = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=timezone.now)

events/forms.py
from datetime import datetime
from django import forms

class CreateEventForm(forms.Form):

    def __init__(self, *args, categories, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["categories"].choices = [(cat.id, cat.name) for cat in categories]

    title = forms.CharField(required=True, label="Nome do evento")
    address = forms.CharField(label="Endereco")
    date = forms.DateField(
        widget=forms.DateInput(attrs={
            'type':'date'
        }),
        label="Data do evento"
    )

    date_release_tickets = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date'
        }),
        label="Data de compra dos Ingressos",
        required=False 
    )

    quantity = forms.IntegerField(label="Quantidade de Ingressos")
    categories = forms.ChoiceField(choices=[], label="Escolha uma categoria")
    description = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        label="Descricao do evento"
    )


from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

events/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import Event, Category, Ticket
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone

from .forms import CreateEventForm, CustomLoginForm, SignUpForm

# Create your views here.

def events_page(request):
    events_list = Event.objects.all()
    return render(request, "events/events.html", {
        "events": events_list, 
        "user": request.user
    })

@login_required
def create_event(request):

    categories = Category.objects.all()

    if request.method == "POST":
        event_form = CreateEventForm(request.POST, categories=categories)

        user = request.user
            
        if event_form.is_valid():

            categories = Category.objects.filter(id__in=event_form.cleaned_data["categories"])

            if not categories.exists():
                
                return render(
                    request,
                    "events/create-event.html", 
                    {
                        "category_error_message":"Selecione uma categoria valida!"
                    }
                )

            date_release_ticket = event_form.cleaned_data.get("date_release_tickets", timezone.now())

            new_event = Event(
                title=event_form.cleaned_data["title"],
                description=event_form.cleaned_data["description"],
                address=event_form.cleaned_data["address"],
                date=event_form.cleaned_data["date"],
                date_release_tickets= date_release_ticket,
                number_ticket=event_form.cleaned_data["quantity"],
                user=user,
            );

            new_event.save()

            new_event.categories.set(categories)
        
            return HttpResponseRedirect(reverse("events:index"))
    
    if request.method == "GET":
        
        context = {
            "form_create_event": CreateEventForm(categories=categories)
        }

        return render(request, "events/create-event.html", context)

    return events_page(request);

def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    current_date = timezone.now().date()
    
    tickets_sold = Ticket.objects.filter(event=event).count()
    quantity_tickets_available = event.number_ticket - tickets_sold;
    
    context = { 
        "event": event,
        "current_date": current_date,
        "can_buy": there_is_ticket_availabe(event_id),
        "tickets_available": quantity_tickets_available
    }

    return render(request, "events/detail.html", context)

@login_required
def buy_ticket(request, event_id):
    user = request.user
    event = get_object_or_404(Event, pk=event_id)

    if there_is_ticket_availabe(event_id=event_id):
        ticket = Ticket(user=user, event=event, code="AAAA", created_at=timezone.now());
        ticket.save()

        return render(request, "events/buy-ticket.html", {
            "event": event,
            "ticket": ticket
        })
    
    else:
        return render(request, "events/no-ticket.html", {"event": event})


def login_page(request): 
    if request.method == "POST":
        login_form = CustomLoginForm(request=request, data=request.POST)
        
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect("/events")
        else:
            return render(request, "accounts/login.html", {"login_form": login_form})


    else:
        login_form = CustomLoginForm()
        return render(request, "accounts/login.html", {"login_form": login_form})

def signup_view(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/events")
    else:
        form = SignUpForm()

    return render(request, "accounts/signup.html", {"form":form})

def logout_view(request):
    logout(request)
    return redirect("/events") 


def there_is_ticket_availabe(event_id):
    event = get_object_or_404(Event, pk=event_id)
    quantity_tickets_sold = Ticket.objects.filter(event=event).count()

    if event.number_ticket <= quantity_tickets_sold:
        return False
    
    return True

events/templates/accounts/login.html
{% extends "events/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div style="width: 400px; margin: 0 auto">

    <h1>Login</h1>
    <form action="{% url 'events:login' %}" method="post">
        {% csrf_token %}
        
        {{ login_form|crispy }}

        <button type="submit" class="btn btn-primary">Logar</button>
    </form>
</div>

{% endblock %}

events/templates/accounts/signup.html
{% extends "events/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div style="width: 400px; margin: 0 auto">
    <h1>Se Cadastrar</h1>
    <form method="post">
        {% csrf_token %}
        
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">SE CADASTRAR</button>
    </form>
</div>

{% endblock %}

events/templates/events/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>Event System</title>
</head>
<body>
    <header>
        <h1>Eventos 2000</h1>
        <nav>
            <a href="{% url 'events:index' %}">Eventos</a>

            {% if user.is_authenticated %}
                <a href="{% url 'events:create_event' %}">Criar novo evento</a>
            {% endif %}
            |
            
            {% if user.is_authenticated %}
                <a href="{% url 'events:logout' %}" class="btn">LOGOUT</a>
            {% else %}
                <a href="{% url 'events:login' %}" class="btn">LOGIN</a>
            {% endif %}
        
            {% if not user.is_authenticated %}
                <a href="{% url 'events:signup' %}" class="btn">SE CADASTRAR</a>
            {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>


    <footer>
        footer
    </footer>
</body>
</html>

events/templates/events/buy-ticket.html
{% extends "events/base.html" %}
{% load static %}

{% block content %}

<h1>Obrigado por comprar o ingresso</h1>
<h2>para o evento: {{event.title}}</h2>
<img src="{% static 'img/minions.webp' %}" alt="how the dev react when you use his app">
<p>Endereco: {{event.address}}</p>
<p>Nao percao o horario: {{event.date}}</p>

<h2>O Codigo do seu ticket eh {{ticket.code}}</h2>
<p>voce pode ver os seus ticekt na pagina </p>

<a href="{% url 'events:index'%}">Voltar aos eventos</a>

{% endblock %}}

events/templates/events/create-event.html
{% extends "events/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <form action="{% url 'events:create_event' %}" method="post" style="width: 400px; margin: 0 auto">
        {% csrf_token %}

        <h2>Criar novo evento</h2>
        {{ form_create_event|crispy }} 
        <button type="submit" class="btn btn-primary">Criar evento</button>
   
    </form>

{% endblock %}

events/templates/events/detail.html
{% extends "events/base.html" %}
{% load static %}

{% block content %}
    <h2>Detalhes: {{event.title}}</h2>

    <p>Local Do Evento: {{event.address}}</p>
    <p>Hora: {{event.date}}</p>
    <p>Ingressos disponiveis: {{tickets_available}} tickets</p>
    
    <img src="{% static 'img/sonic.jpg' %}" alt="Sonic mad" width="400" height="200">

    <p>Description: {{event.description}}</p>

    {% if can_buy %}
        {% if event.date_release_tickets > current_date %}
            <p>Os ingressos ainda nao estao disponiveis para venda</p>
            <a class="btn btn-warning">Me Avise</a>
        {% else %}
            <a href="{% url 'events:buy_ticket' event.id %}" class="btn btn-primary">Comprar Ingresso</a>
        {% endif %}
    {% else %}
        <p>Ingressos esgotados</p>
    {% endif %}




{% endblock %}

events/templates/events/events.html
{% extends "events/base.html" %}

{% block content %}
    <h2>Lista de eventos disponiveis</h2>

    {% if events %}
        <div>
            <ul>
                {% for event in events %}
                    <li>
                        <h1>{{ event.title }}</h1>
                        <p>{{ event.description }}</p>
                        <p>Quando: {{event.date}}</p>
                        <p>Local: {{event.address}}</p>
                        <p>Descricao: {{event.description}}</p>
                        
                        {% for category in event.categories.all %}
                            <span> {{category.name}}</span>
                        {% endfor %}
                        
                        <br/>

                        <a href="{% url 'events:event_details' event.id %}">Ver Detalhes</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    
    {% else %}
        <b><h3>Nenhum evento novo....</h3></b>
    {% endif %}

{% endblock %}

events/templates/events/no-ticket.html
{% extends "events/base.html" %}
{% load static %}

{% block content %}
    <h1>Infelizmente os ingressos para o Evento: {{event.title}} esgotaram</h1>
    
    <h2>Voce ficou indecisso e demorou muito para comprar seu ingresso e eles fugiram</h2>
    <p>ou esgotaram</p>

    <img src="{% static 'img/button.jpg' %}" alt="os ingressos acabaram" width="300px">

    <p>mas nao se preocupe voce ainda pode participar de outros eventos <a href="{% url 'events:index' %}">aqui</a></p>
{% endblock %}